// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flash-1': string;
  'flash-2': string;
  'flash-3': string;
  'lightrope': string;
}
export const cssExports: CssExports;
export default cssExports;
