// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatarWrapper': string;
  'bounce': string;
  'buttonWrapper': string;
  'close': string;
  'error': string;
  'form': string;
  'presenteeWishlist': string;
  'presenteeWishlistWrapper': string;
  'waitMsg': string;
  'wannaBe': string;
  'wishlistMsg': string;
}
export const cssExports: CssExports;
export default cssExports;
