// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatarWrapper': string;
  'bounce': string;
  'buttonWrapper': string;
  'wannaBe': string;
  'wishlist': string;
}
export const cssExports: CssExports;
export default cssExports;
