// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'crack': string;
  'cracker': string;
  'cracker-left': string;
  'cracker-left-inner': string;
  'cracker-left-zigzag': string;
  'cracker-left-zigzag__item': string;
  'cracker-left__body': string;
  'cracker-left__end': string;
  'cracker-left__mask-bottom': string;
  'cracker-left__mask-top': string;
  'cracker-left__tail': string;
  'cracker-message': string;
  'cracker-message__inner': string;
  'cracker-right': string;
  'cracker-right-inner': string;
  'cracker-right-zigzag': string;
  'cracker-right-zigzag__item': string;
  'cracker-right__body': string;
  'cracker-right__end': string;
  'cracker-right__mask-bottom': string;
  'cracker-right__mask-top': string;
  'cracker-right__tail': string;
  'cracksBg': string;
  'hover-me-text': string;
}
export const cssExports: CssExports;
export default cssExports;
