// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'snowflake': string;
  'snowflakes-fall': string;
  'snowflakes-shake': string;
}
export const cssExports: CssExports;
export default cssExports;
