// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'tab': string;
  'tabContent': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
